{"name": "# Verify phone \"310.817.0370\" is here", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.MoveTargetOutOfBoundsException: Message: (167, 1586) is out of bounds of viewport width (1280) and height (607)\n\n", "trace": "  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\003_main_page_phone_here.py\", line 8, in vrf_phn_here\n    context.app.main_page.vrf_phn_here(phone)\n  File \"C:\\Everything\\IT\\Testing\\Automation_08_09_2019\\autocareparts_gene_kayakov\\pages\\main_page.py\", line 83, in vrf_phn_here\n    actions.perform()\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\selenium\\webdriver\\common\\action_chains.py\", line 80, in perform\n    self.w3c_actions.perform()\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\selenium\\webdriver\\common\\actions\\action_builder.py\", line 76, in perform\n    self.driver.execute(Command.W3C_ACTIONS, enc)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given Loginpage", "status": "passed", "start": 1612659355170, "stop": 1612659356071}, {"name": "Then Verify phone \"310.817.0370\" is here", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.MoveTargetOutOfBoundsException: Message: (167, 1586) is out of bounds of viewport width (1280) and height (607)\n\n", "trace": "  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\003_main_page_phone_here.py\", line 8, in vrf_phn_here\n    context.app.main_page.vrf_phn_here(phone)\n  File \"C:\\Everything\\IT\\Testing\\Automation_08_09_2019\\autocareparts_gene_kayakov\\pages\\main_page.py\", line 83, in vrf_phn_here\n    actions.perform()\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\selenium\\webdriver\\common\\action_chains.py\", line 80, in perform\n    self.w3c_actions.perform()\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\selenium\\webdriver\\common\\actions\\action_builder.py\", line 76, in perform\n    self.driver.execute(Command.W3C_ACTIONS, enc)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1612659356072, "stop": 1612659362241}], "start": 1612659347830, "stop": 1612659363717, "uuid": "abe4db5c-3ea6-47a8-b7c1-affd9b829c66", "historyId": "13811a0c003581d411a5a230904ac2b3", "fullName": "# Verify phone \"310.817.0370\" is here: # Verify phone \"310.817.0370\" is here", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "# Verify phone \"310.817.0370\" is here"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}